---

- name: write nginx configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ item }}"
  with_items:
    - zipballs.nginx.conf
    - app.nginx.conf
  sudo: yes

- name: enable nginx configuration
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items:
    - zipballs.nginx.conf
    - app.nginx.conf
  sudo: yes

- name: check if nginx has default symbolic linked website file
  stat: path=/etc/nginx/sites-enabled/default
  register: nginx_default_file

- name: delete default symbolic linked website on nginx
  command: rm /etc/nginx/sites-enabled/default
  sudo: yes
  when: nginx_default_file.stat.exists
  notify:
    - restart nginx
